# Model training lab

This is the notebook for loading and training models.
Furthermore it provides simple documentation for different approaches used for training a model.

Run the command below to see command-completion on pressing `TAB`.

## Prerequisits

In [15]:
# Imports
import os
import warnings
import tools
import models as c_models
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.layers import Bidirectional

# Ignore future warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Root CSV files directory
dirname = "./data/"

# Constant frame count.
frames = 100

## Preparation Stage
### Load data and normalize
For training it's required to extend/reduce every dataset to n frames, where n is `frames`.

In [16]:
listfile = os.listdir(dirname)
contents = []
for wordname in listfile:
    if wordname == ".DS_Store":
        continue
    for csv in os.listdir(dirname + wordname):
        filepath = os.path.join(dirname, wordname, csv)
        content = pd.read_csv(filepath, sep=';')
        content = content.reindex(list(range(0, frames)), fill_value=0.0)
        content.fillna(0.0, inplace = True) 
        contents.append((wordname, content))
data = contents

In [17]:
# Print the content of the first dataframe
contents[0][1]

face_x    face_y  landmark_x_1  landmark_y_1  landmark_x_2  \
0   0.470624  0.313346      0.639333      0.944016      0.588136   
1   0.470841  0.318451      0.351937      0.960826      0.411960   
2   0.469118  0.320056      0.365665      0.956447      0.420067   
3   0.469637  0.320771      0.380982      0.957185      0.429653   
4   0.471696  0.319425      0.387040      0.958757      0.441715   
..       ...       ...           ...           ...           ...   
95  0.000000  0.000000      0.000000      0.000000      0.000000   
96  0.000000  0.000000      0.000000      0.000000      0.000000   
97  0.000000  0.000000      0.000000      0.000000      0.000000   
98  0.000000  0.000000      0.000000      0.000000      0.000000   
99  0.000000  0.000000      0.000000      0.000000      0.000000   

    landmark_y_2  landmark_x_3  landmark_y_3  landmark_x_4  landmark_y_4  ...  \
0       0.923641      0.561776      0.890851      0.577628      0.867982  ...   
1       0.935828      0.435300      0.886520      0.435451      0.847356  ...   
2       0.908137      0.447947      0.849639      0.436687      0.799112  ...   
3       0.899122      0.453137      0.833393      0.440341      0.774351  ...   
4       0.887443      0.464157      0.826509      0.456501      0.775087  ...   
..           ...           ...           ...           ...           ...  ...   
95      0.000000      0.000000      0.000000      0.000000      0.000000  ...   
96      0.000000      0.000000      0.000000      0.000000      0.000000  ...   
97      0.000000      0.000000      0.000000      0.000000      0.000000  ...   
98      0.000000      0.000000      0.000000      0.000000      0.000000  ...   
99      0.000000      0.000000      0.000000      0.000000      0.000000  ...   

    landmark_x_38  landmark_y_38  landmark_x_39  landmark_y_39  landmark_x_40  \
0        0.000000       0.000000       0.000000       0.000000       0.000000   
1        0.619671       0.821530       0.683979       0.790299       0.677252   
2        0.605166       0.822862       0.669363       0.795220       0.663645   
3        0.603590       0.823892       0.661824       0.792022       0.660768   
4        0.597416       0.806157       0.656806       0.783026       0.648856   
..            ...            ...            ...            ...            ...   
95       0.000000       0.000000       0.000000       0.000000       0.000000   
96       0.000000       0.000000       0.000000       0.000000       0.000000   
97       0.000000       0.000000       0.000000       0.000000       0.000000   
98       0.000000       0.000000       0.000000       0.000000       0.000000   
99       0.000000       0.000000       0.000000       0.000000       0.000000   

    landmark_y_40  landmark_x_41  landmark_y_41  landmark_x_42  landmark_y_42  
0        0.000000       0.000000       0.000000       0.000000       0.000000  
1        0.774806       0.654642       0.813162       0.638180       0.845178  
2        0.791355       0.640720       0.825665       0.622981       0.855132  
3        0.776878       0.641793       0.811655       0.624695       0.842568  
4        0.743433       0.629925       0.785155       0.613204       0.822693  
..            ...            ...            ...            ...            ...  
95       0.000000       0.000000       0.000000       0.000000       0.000000  
96       0.000000       0.000000       0.000000       0.000000       0.000000  
97       0.000000       0.000000       0.000000       0.000000       0.000000  
98       0.000000       0.000000       0.000000       0.000000       0.000000  
99       0.000000       0.000000       0.000000       0.000000       0.000000  

[100 rows x 86 columns]

### Split data
Split the dataset up into the following segments:
1. Training Data: 60%
2. Validation Data: 20%
3. Test Data: 20%


In [18]:
features = [n[1] for n in data]
features = [f.to_numpy() for f in features]
labels = [n[0] for n in data]
x_train, x_val, y_train, y_val = train_test_split(features, labels, test_size=0.40, random_state=42)
x_val, x_test, y_val, y_test = train_test_split(x_val, y_val, test_size=0.50, random_state=42)

In [19]:
# Display data distribution
print("Total:", len(labels))
print("Training:", len(y_train), len(y_train) / len(labels) * 100)
print("Val:", len(y_val), len(y_val) / len(labels) * 100)
print("Test:", len(y_test), len(y_test) / len(labels) * 100)

Total: 347
Training: 208 59.94236311239193
Val: 69 19.88472622478386
Test: 70 20.172910662824208


### Tokenize (One Hot)

In [20]:
import tools
tokenizer = tools.tokenize(dirname)
print(tokenizer.word_index)
encoded_train=tokenizer.texts_to_sequences([y_train])[0]
encoded_val=tokenizer.texts_to_sequences([y_val])[0]
encoded_test=tokenizer.texts_to_sequences([y_test])[0]
y_train = to_categorical(encoded_train)
y_val = to_categorical(encoded_val)
y_test = to_categorical(encoded_test)
print(y_train)

{'welt': 1, 'deutschland': 2, 'hallo': 3, 'computer': 4}
[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [21]:
# Making numpy arrays
x_train=np.array(x_train)
y_train=np.array(y_train)
x_val=np.array(x_val)
y_val=np.array(y_val)
x_test=np.array(x_test)
y_test=np.array(y_test)

In [22]:
print(y_train)

[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


## Training Stage
Configure the model and train it.

Metrics:
![accuracy](assets/accuracy.png)
![precision and recall formula](assets/precision_recall_formula.png)
![precision and recall](assets/precision_recall.png)


### Configure model
Configures the model with the specified parameters.

#### LSTM

In [9]:
model = Sequential()
model.add(layers.LSTM(64, return_sequences=True,
               input_shape=(100, 86)))  # returns a sequence of vectors of dimension 32
model.add(layers.LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(layers.LSTM(32))  # return a single vector of dimension 32
model.add(layers.Dense(5, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy',tf.keras.metrics.Precision(),tf.keras.metrics.Recall()])

#### Bidirectional LSTM

In [28]:
model = Sequential()
model.add(Bidirectional(layers.LSTM(64, return_sequences=True), input_shape=(100, 86)))
model.add(layers.Bidirectional(layers.LSTM(32)))
model.add(layers.Dense(5, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) 

#### Simple RNN

In [ ]:
model = Sequential()
model.add(SimpleRNN(units=64, input_shape=(200, 42)))
model.add(Dense(64, activation="softmax")) #softmax, linear 어떤걸 기준으로 하지
model.add(Dense(128, activation="linear")) #softmax, linear 어떤걸 기준으로 하지
model.add(Dense(21))
model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

### Train

In [29]:
history=model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_val,y_val))

Train on 208 samples, validate on 69 samples
Epoch 1/100
208/208 [==============================] - 12s 58ms/sample - loss: 1.4134 - accuracy: 0.4471 - val_loss: 1.2017 - val_accuracy: 0.6232
Epoch 2/100
208/208 [==============================] - 3s 15ms/sample - loss: 1.1235 - accuracy: 0.6635 - val_loss: 0.9606 - val_accuracy: 0.7826
Epoch 3/100
208/208 [==============================] - 3s 16ms/sample - loss: 0.8851 - accuracy: 0.8125 - val_loss: 0.7765 - val_accuracy: 0.8406
Epoch 4/100
208/208 [==============================] - 3s 16ms/sample - loss: 0.6905 - accuracy: 0.8269 - val_loss: 0.6250 - val_accuracy: 0.8406
Epoch 5/100
208/208 [==============================] - 3s 17ms/sample - loss: 0.5298 - accuracy: 0.8702 - val_loss: 0.5252 - val_accuracy: 0.8261
Epoch 6/100
208/208 [==============================] - 4s 17ms/sample - loss: 0.4889 - accuracy: 0.8510 - val_loss: 0.5496 - val_accuracy: 0.7971
Epoch 7/100
208/208 [==============================] - 4s 17ms/sample - loss: 

208/208 [==============================] - 4s 19ms/sample - loss: 0.1362 - accuracy: 0.9519 - val_loss: 0.3649 - val_accuracy: 0.9130
Epoch 57/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.1167 - accuracy: 0.9615 - val_loss: 0.3286 - val_accuracy: 0.9275
Epoch 58/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.0999 - accuracy: 0.9760 - val_loss: 0.3072 - val_accuracy: 0.9420
Epoch 59/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.0962 - accuracy: 0.9712 - val_loss: 0.3951 - val_accuracy: 0.9130
Epoch 60/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.1096 - accuracy: 0.9663 - val_loss: 0.3616 - val_accuracy: 0.8841
Epoch 61/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.0814 - accuracy: 0.9808 - val_loss: 0.3007 - val_accuracy: 0.9130
Epoch 62/100
208/208 [==============================] - 4s 18ms/sample - loss: 0.0815 - accuracy: 0.9808 - val_loss: 0.4748 - val_a

### Evaluate

In [30]:
model.evaluate(x=x_test, y=y_test, batch_size=32)

70/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.18593052914366126, 0.94285715]

### Save model

In [12]:
model.save("sign_lang_recognition.h5")